-- Mazání dat ze všech tabulek
DELETE FROM review;
DELETE FROM order_product;
DELETE FROM shipment;
DELETE FROM payment;
DELETE FROM order_entity;
DELETE FROM user;
DELETE FROM product_cart;
DELETE FROM product_size;
DELETE FROM product_category;
DELETE FROM product;
DELETE FROM cart;
DELETE FROM manufacturer;
DELETE FROM address;
DELETE FROM category;

-- Mazání tabulek
DROP TABLE review;
DROP TABLE order_product;
DROP TABLE shipment;
DROP TABLE payment;
DROP TABLE order_entity;
DROP TABLE user;
DROP TABLE product_cart;
DROP TABLE product_size;
DROP TABLE product_category;
DROP TABLE product;
DROP TABLE cart;
DROP TABLE manufacturer;
DROP TABLE address;
DROP TABLE category;
